// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1:string,arg2:string):Promise<void>;

export function List(arg1:string):Promise<Array<string>>;

