// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['services']['RepoService']['Create'](arg1, arg2);
}

export function Open(arg1) {
  return window['go']['services']['RepoService']['Open'](arg1);
}

export function Recent() {
  return window['go']['services']['RepoService']['Recent']();
}
